### server config
server:
  port: 5000
#  address: 127.0.0.1
#  use-forward-headers: true

  # server error config
  error:
    include-stacktrace: ON_TRACE_PARAM
    path: /error # Path of the error controller.
    whitelabel:
      enabled: true

security:
  require-ssl: true

### health endpoints
endpoints:
  health:
    sensitive: false
  liquibase:
    enabled: true

### health and trace config
management:
  # health config
  health:
    db:
      enabled: true
    defaults:
      enabled: true
    diskspace:
      enabled: true

liquibase:
  enabled: true
  change-log: classpath:db/changelog/db.changelog-master.xml
  checkChangeLogLocation: true
  url: "jdbc:postgresql://localhost:5432/postgres"
  user: jo5h0y4
  password: "admin"

h2:
  console:
    enabled: true
   
### spring config
spring:
  profiles:
    active: dev
  mail:
    host: smtp-relay.gmail.com
    port: 587
    username: msg@bikedeed.io
    password: bikedeed.io.password
    protocol: smtp
    defaultEncoding: UTF-8
    properties:
      mail:
        socketFactory:
          port: 587
          class: javax.net.ssl.SSLSocketFactory
          fallback: false
        smtp:
          starttls:
            enable: true
            required: true
            auth: true
          
  # html cache
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    
  #### spring data source
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: jo5h0y4
    password: "admin"
    
  # trace config
  trace:
    include: parameters,errors,query_string,path_info,context_path

    ### tomcat connection pool setting
    tomcat:
      max-active: 5
      max-idle: 5
      min-idle: 0
      initial-size: 1
      max-wait: 30000
      max-age: 25000
      validation-query: "SELECT 1"
      validation-interval: 15000
      test-on-borrow: true

  ### spring jackson serialization config
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ssXXX
    mapper:
      accept_case_insensitive_properties: false
    serialization:
      write_dates_as_timestamps: false
      write-empty-json-arrays: false
    default-property-inclusion: NON_EMPTY
    deserialization:
      fail_on_unknown_properties: false
      adjust_dates_to_context_time_zone: false
      accept_single_value_as_array: true
  
### mybatis
mybatis:
  mapper-locations: classpath*:mybatis/mappers/*.xml
  type-aliases-package: com.bike.dto
  type-handlers-package: com.bike.dto.typehandler
  executor-type: REUSE
  configuration.default-statement-timeout: 10
  configuration.default-fetch-size: 1000

### spring-fox swagger
springfox:
  documentation:
    swagger:
      contactName: Jorge M Spiropulo
      title: BikeDeed
      version: 1.0.0
      description: |+
        BikeDeed Application
      contactUrl: http://www.bike.com
      contactEmail: spiropulo@gmail.com
      v2:
        path: /api-docs